### ISSUE TITLE
`--sample-unit` causes an error 

### ISSUE THREAD

**Issue by chekos** [chekos/pypums#273]
## 🔬 How To Reproduce

1. run `pypums download-acs --year 2018 --state alaska --sample-unit household` on mybinder link

### Code sample

```shell
pypums download-acs --year 2018 --state alaska --sample-unit household
```

### Environment

* OS: [e.g. Linux / Windows / macOS]
* Python version, get it with:

```bash
python --version
```

Linux. python 3.7

### Screenshots

<img width="1404" alt="Screen Shot 2022-02-22 at 17 24 04" src="https://user-images.githubusercontent.com/28694175/155247355-b63ab389-d80a-4500-ad66-284f24e2052a.png">

## 📈 Expected behavior

Download a household-level dataset

## 📎 Additional context

Error:
```shell
jovyan@jupyter-chekos-2dpypums-2dgdr3re8j:~$ pypums download-acs --year 2018 --state alaska --sample-unit household
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/pypums", line 8, in <module>
    sys.exit(cli())
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pypums/cli.py", line 94, in download_acs
    _download_data(url, "acs", data_directory, extract)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/pypums/utils.py", line 125, in _download_data
    total = int(response.headers["Content-Length"])
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/httpx/_models.py", line 993, in __getitem__
    raise KeyError(key)
KeyError: 'Content-Length'
```

**Comment by chekos** [comment]
<img width="1249" alt="Screen Shot 2022-02-22 at 17 55 28" src="https://user-images.githubusercontent.com/28694175/155249833-cc0abcb8-4509-4b49-a0cd-ef5a7d3da12f.png">



getting `['content-length']` may fail at first  but shows up in the Headers if you pinged the URL again
